### ISSUE TITLE
Interesting project!

### ISSUE THREAD

**Issue by GabiGrin** [project-coc/flyde-coc-tools#1]
Hey @akim-muto, would love to personally help with whatever you're up to here and support Flyde's early adopters.
PS: huge Japan lover 🙌🏻

**Comment by akim-muto** [comment]
Hi! Thank you your suport!!

I have some ideas and would like to formulate them bit by bit.
From now on I will be very happy if my feedback is useful for you and Flyde in the development.

Best regards!

**Comment by GabiGrin** [comment]
🍻
